;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="AI.Event.Damage",DevComment="")
+GameplayTagList=(Tag="AI.Event.Destroy",DevComment="")
+GameplayTagList=(Tag="AI.Event.Die",DevComment="")
+GameplayTagList=(Tag="AI.Event.TargetFind",DevComment="")
+GameplayTagList=(Tag="AI.Event.TargetLost",DevComment="")
+GameplayTagList=(Tag="AI.Event.Waiting",DevComment="")
+GameplayTagList=(Tag="AI.Event.Patrol",DevComment="")

